project:
  type: website

website:
  title: "Thread Docs"
  description: "Where technical writing meets cross-stitch artistry"
  navbar:                  
    left:
      - href: index.qmd
        text: Home
      - text: Projects
        menu:
          - href: projects.qmd
            text: Gallery View
          - text: "---"
          - href: projects/baby-koala.qmd
            text: Baby Koala
          - href: projects/wedding-sampler-maura-kevin.qmd
            text: Wedding Sampler
          - href: projects/blue-jay.qmd
            text: Blue Jay
          - href: projects/cardinals-couple.qmd
            text: Cardinals Couple
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/amrapalisaha
        
format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    code-copy: false
    link-external-newwindow: true
    link-external-icon: true
    include-after-body:
      text: |
        <script src="/assets/lightbox.js"></script>